apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    environment: development
spec:
  containers:
  - name: backend
    image: matei97/hello-world-nodejs:latest
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"